#ifndef TERMINALEXPLORER_COMMANDMODE_CREATE_FILE_H
#define TERMINALEXPLORER_COMMANDMODE_CREATE_FILE_H
void create_file(char *filename, char *path_for_file);
#endif //TERMINALEXPLORER_COMMANDMODE_CREATE_FILE_H