/* Name: Nilabja Bhattacharya Roll: 2018201036 */
#ifndef TERMINALEXPLORER_COMMANDMODE_CREATE_DIRECTORY_H
#define TERMINALEXPLORER_COMMANDMODE_CREATE_DIRECTORY_H
int create_directory(char *filename, char *path_for_directory);
#endif //TERMINALEXPLORER_COMMANDMODE_CREATE_DIRECTORY_H