/* Name: Nilabja Bhattacharya Roll: 2018201036 */
#ifndef TERMINALEXPLORER_COMMANDMODE_DELETE_DIRECTORY_H
#define TERMINALEXPLORER_COMMANDMODE_DELETE_DIRECTORY_H
int delete_directory(char *path_name_for_directory);
#endif //TERMINALEXPLORER_COMMANDMODE_DELETE_DIRECTORY_H