#ifndef TERMINALEXPLORER_COMMANDMODE_MAKE_SOURCE_DIRECTORY_H
#define TERMINALEXPLORER_COMMANDMODE_MAKE_SOURCE_DIRECTORY_H
void make_source_directory(char *path_name_for_directory_to_be_copied, char *path_to_new_directory);
#endif //TERMINALEXPLORER_COMMANDMODE_MAKE_SOURCE_DIRECTORY_H