#ifndef TERMINALEXPLORER_COMMANDMODE_MOVE_DIRECTORY_H
#define TERMINALEXPLORER_COMMANDMODE_MOVE_DIRECTORY_H
int move_directory(char *path_name_for_directory_to_be_moved, char *path_to_new_directory);
#endif //TERMINALEXPLORER_COMMANDMODE_MOVE_DIRECTORY_H