#ifndef TERMINALEXPLORER_COMMANDMODE_SEARCH_FILE_OR_DIRECTORY_H
#define TERMINALEXPLORER_COMMANDMODE_SEARCH_FILE_OR_DIRECTORY_H
void search_file_or_directory(char *path_name_for_directory_to_be_traversed, char *file_or_folder_name, char *root_path_name);
#endif //TERMINALEXPLORER_COMMANDMODE_SEARCH_FILE_OR_DIRECTORY_H